name: Package

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          manifest-path: pyproject.toml
          cache: true
          frozen: true

      - name: Build conda package
        run: |
          pixi build

      - name: Install conda package
        run: |
          PACKAGE_NAME=`ls *.conda`
          pixi global install --path $PACKAGE_NAME

      - name: Ensure CLI works
        run: |
          hdf-info --help
